/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.mainChart;

import com.raven.chart.*;
import java.awt.Color;
import prisonmanagement.controller.CriminalController;
import prisonmanagement.view.DashboardView;

/**
 *
 * @author RAVEN
 */
public class CriminalChartMain extends javax.swing.JFrame {

    /**
     * Creates new form VisitorChartMain
     */
    private final CriminalController criminalController;
    
    public CriminalChartMain() {
        initComponents();
        this.criminalController = new CriminalController();
        getContentPane().setBackground(new Color(250, 250, 250));
        chart.addLegend("Ít Nghiêm Trọng", new Color(245, 189, 135));
        chart.addLegend("Nghiêm Trọng", new Color(135, 189, 245));
        chart.addLegend("Rất Nghiêm Trọng", new Color(189, 135, 245));
        chart.addLegend("Đặc Biệt Nghiêm Trọng", new Color(139, 229, 222));
        chart.addData(new ModelChart("Mức độ tội phạm", this.criminalController.countCriminal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        chart = new com.raven.chart.Chart();
        BackButton = new prisonmanagement.view.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BackButton.setBorder(null);
        BackButton.setForeground(new java.awt.Color(60, 29, 25));
        BackButton.setText("Back");
        BackButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BackButton.setRadius(25);
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CRIMINAL CHART");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        chart.start();
    }                                 

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        this.dispose();
    }                                          

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private prisonmanagement.view.MyButton BackButton;
    private com.raven.chart.Chart chart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   

}
